### ISSUE TITLE
Students can pass the tests just by using the relationship between index and _id

### ISSUE THREAD

**Issue by cofauver** [SF-WDI-LABS/test-driven-todo-api#17]
On GET or PUT '/api/todos/:id'  students were able to just respond with or edit `todos[req.params.id - 1]` and pass the tests. While they have satisfied the general requirement of returning/updating the correct thing in this case, this solution fails when you delete and then GET or PUT. Once you've taken an element out of the array, the relationship between index and id is broken.

**Comment by nathanallen** [comment]
I propose we sever the relationship between index/_id by using non-consecutive integers ( e.g. 3, 88, 97) in the stubbed todos data.
